openapi: 3.0.0
info:
  title: Каталог товаров
  description: Спецификация для работы с каталогом товаров
  version: 1.0.0
  contact:
    name: Янчук Надежда
    email: nadiaianciuk@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8000
    description: Development server
tags:
  - name: Категории
    description: Категории товаров
  - name: Товары
    description: Товары
paths:
  /categories:
    get:
      summary: Получение списка категорий
      tags:
        - Категории
      responses:
        '200':
          description: Список категорий
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Добавление новой категории
      tags:
        - Категории
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Название категории
      responses:
        '201':
          description: Новая категория создана успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Название категории
        '400':
          description: Некорректные данные для создания категории
  '/categories/{id}':
    get:
      summary: Получение информации о категории
      tags:
        - Категории
      responses:
        '200':
          description: Информация о категории
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Название категории
    put:
      summary: Обновление информации о категории
      tags:
        - Категории
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Название категории
      responses:
        '200':
          description: Информация о категории успешно обновлена
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Название категории
        '400':
          description: Некорректные данные для обновления информации о категории
        '404':
          description: Категория не найдена
    delete:
      summary: Удаление категории
      tags:
        - Категории
      responses:
        '204':
          description: Категория успешно удалена
        '404':
          description: Категория не найдена
  /products:
    get:
      summary: Получение списка товаров
      tags:
        - Товары
      responses:
        '200':
          description: Список товаров
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
    post:
      summary: Добавление нового товара
      tags:
        - Товары
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        '201':
          description: Новый товар создан успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        '400':
          description: Некорректные данные для создания товара
    '/products/{id}':
     get:
      summary: Получение информации о товаре
      tags:
        - Товары
      responses:
        '200':
          description: Информация о товаре
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Название товара
    put:
      summary: Обновление информации о товаре
      tags:
        - Товары
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        '200':
          description: Информация о товаре успешно обновлена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        '400':
          description: Некорректные данные для обновления информации о товаре
        '404':
          description: Товар не найден
    delete:
      summary: Удаление товара
      tags:
        - Товары
      responses:
        '204':
          description: Товар успешно удален
        '404':
          description: Товар не найден
components:
  schemas:
    Product:
      type: object
      required:
        - name
        - category
        - price
      properties:
        name:
          type: string
          description: Название товара
        category:
          type: string
          description: Категория товара
        description:
          type: string
          description: Описание товара
        price:
          type: number
          description: Цена товара
        model:
          type: string
          description: Модель товара
        color:
          type: string
          description: Цвет товара