openapi: 3.0.0
info:
  title: Каталог товаров
  description: Спецификация для работы с каталогом товаров
  version: 1.0.0
  contact:
    name: Янчук Надежда
    email: nadiaianciuk@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8000
    description: Development server
tags:
  - name: Категории
    description: Категории товаров
  - name: Товары
    description: Товары
paths:
  /api/categories:
    get:
      summary: Получение списка категорий
      tags:
        - Категории
      responses:
        '200':
          description: Список категорий
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Categories'
    post:
      summary: Добавление новой категории
      tags:
        - Категории
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Categories'
      responses:
        '201':
          description: Новая категория создана успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categories'
        '400':
          description: Некорректные данные для создания категории
  /api/categories/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Идентификатор категории
        schema:
          type: integer
          minimum: 1
    get:
      summary: Информация о категории
      tags:
        - Категории
      responses:
        '200':
          description: Категория успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categories'
        '404':
          description: Категория с указанным ID не найдена
    put:
      summary: Обновление информации о категории
      tags:
        - Категории
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Categories'
      responses:
        '200':
          description: Категория успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categories'
        '404':
          description: Категория с указанным ID не найдена
    delete:
      summary: Удаление категории
      tags:
        - Категории
      responses:
        '204':
          description: Категория успешно удалена
        '404':
          description: Категория не найдена
  /api/products:
    get:
      summary: Получение списка товаров
      tags:
        - Товары
      responses:
        '200':
          description: Список товаров
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Добавление нового товара
      tags:
        - Товары
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Новый товар создан успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Некорректные данные для создания товара
  /api/products/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Идентификатор товара
        schema:
          type: integer
          minimum: 1
    get:
      summary: Информация о товаре
      tags:
        - Товары
      responses:
        '200':
          description: Товар успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Товар с указанным ID не найден
    put:
      summary: Обновление информации о товаре
      tags:
        - Товары
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        '200':
          description: Информация о товаре успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Некорректные данные для обновления информации о товаре
        '404':
          description: Товар не найден
    delete:
      summary: Удаление товара
      tags:
        - Товары
      responses:
        '204':
          description: Товар успешно удален
        '404':
          description: Товар не найден
components:
  schemas:
    Categories:
      type: object
      properties:
        id:
          type: integer
          description: Идентификатор товара
        name:
          type: string
          description: Название категории
        description:
          type: string
          description: Описание категории
        mark:
          type: boolean
          description: Статус категории
        status:
          type: boolean
          description: Наличие категории
        order:
          type: number
          description: ID категории
      required:
        - id
        - name
    Product:
      type: object
      required:
        - id
        - name
        - image
        - price
        - quantity
      properties:
        id:
          type: integer
          description: Идентификатор товара
        name:
          type: string
          description: Название товара
        description:
          type: string
          description: Описание товара
        image: 
          type: string
          description: Фото товара
        price:
          type: number
          description: Цена товара
        quantity:
          type: number
          description: Статус товара
        brand:
          type: string
          description: Бренд товара
        mark:
          type: boolean
          description: Статус товара
        status:
          type: boolean
          description: Наличие товара
        discount:
          type: number
          description: Скидка
        model:
          type: string
          description: Модель товара
        color:
          type: string
          description: Цвет товара